### ISSUE TITLE
3D time series output ?

### ISSUE THREAD

**Issue by nyue** [microhh/microhh#52]
Hi,

  I build and ran microhh on two examples couette and rico

  I see a NetCDF file and was hoping to get the 3D timeseries data from the file but I see that only the z dimension is written out.

  Which examples should I run to get x,y,z dimension plus t (unlimited) ? I wish to generate some data for visualization tests.

Cheers

**Comment by Chiil** [comment]
We do not save 3d time series by default, because of the excessive amount of data generated for large cases. You could save the restart files more often (savetime) and process your own netcdf file from those files. There is a python script that can convert raw binary into netcdf in the Python folder.

There is also the dump module that allows you to save fields that are not prognostic variables.

Chiel
