### ISSUE TITLE
User changes to `rte-rrtmgp-cpp` submodule.

### ISSUE THREAD

**Issue by julietbravo** [microhh/microhh#85]
Users who clone MicroHH from their fork still get the `rte-rrtmgp-cpp` submodule from the MicroHH repository. How/where should users commit/push changes to the radiation code? The only method would be to manually fork `rte-rrtmgp-cpp`, commit the changes there, and then somehow try to use their `rte-rrtmgp-cpp` fork as the submodule......?

**Comment by thijsheus** [comment]
That's a question I had myself :) This should be somewhere in the documentation...

**Comment by Chiil** [comment]
I am afraid that there is no simple solution here. The radiation code comes from an external repo, so the only option is to fork that repo and use your own fork, or to send a pull request to the radiation code and then pull in the new upstream code. Adding the repo via `git` instead of `https` doesn't make it a lot easier too for users that just want to check out the code.
